service: reqdash-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    REQRES_BASE_URL: https://reqres.in/api
    REQRES_API_KEY: ${env:REQRES_API_KEY}
    CORS_ORIGINS: ${env:CORS_ORIGINS}
    NODE_ENV: production

functions:
  api:
    handler: dist/lambda.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
